automatic_cashier/automatic_cashier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cashier.urls'))
]

automatic_cashier/cashier/urls.py
from django.urls import path, include
from . import views

app_name = 'cashier'

urlpatterns = [
    path("",views.index, name='index'),
    path("sign_up/", views.sign_up, name='sign_up'),
    path('card_activation/', views.card_activation, name='card_activation'),
    path('menu/', views.menu, name='menu'),
    path('logout/', views.logout_user, name='logout'),
    path('check_balance/', views.check_balance, name='check_balance'),
    path('card_validation/<int:trans>/<int:tries>/', views.card_validation, name='card_validation'),
    path('deposit/', views.deposit, name='deposit'),
    path('deposit_money/', views.deposit_money, name='deposit_money'),
    path('purchase_tickets/', views.purchase_tickets, name='purchase_tickets'),
    path('withdraw_money/', views.withdraw_money, name='withdraw_money')
]

automatic_cashier/cashier/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    direction = models.TextField(default="not apply")
    cellphone = models.CharField(max_length=10, default='not apply')
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=150, unique=False, null=True, blank=True)
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['password', 'password2']

    def __str__(self):
        return f'{self.first_name} {self.last_name}' 


class Account(models.Model):
    balance = models.FloatField(default=999999.99)
    opening_date = models.DateField(auto_now_add=True)
    client = models.ForeignKey(User, on_delete= models.CASCADE)

    def __str__(self):
        return f'{self.client} account'

    def show_balance(self):
        return self.balance


class CreditCard(models.Model):
    account = models.OneToOneField(Account, on_delete=models.CASCADE, default=1)
    password = models.CharField(max_length=4, unique=True)
    id_limit  = models.IntegerField(default=3)        
    activation = models.BooleanField(default=True)

    def block_credit_card(self):
        self.activation = False

class Cashier(models.Model):
    location = models.CharField(max_length=100, default="not apply")
    available_balance = models.FloatField()
    affiliated_bank = models.CharField(max_length=100, default="bank")
    max_withdrawal_amount = models.FloatField() 
    CreditCards = models.ManyToManyField(CreditCard, related_name="credit_cards")    

automatic_cashier/cashier/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User, CreditCard
from django import forms

class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label= "Password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password','placeholder':'password', 'id': 'password'}),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email','cellphone','direction','password1', 'password2']
        widgets= {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write your first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write your last name'}),

            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'write your email'}),
            'direction': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write your direction'}),
            'cellphone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'write a valid cellphone'}),
        }

class CardActivation(ModelForm):
    password = forms.CharField(
        label= "Credit Card Password Set Up",
        widget=forms.PasswordInput(attrs={'class':'form-control password', 'type':'password','placeholder':'####', 'id': 'password', 'maxlength': '4'}),
    )       
    class Meta:
        model = CreditCard
        fields = ['password']

automatic_cashier/cashier/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import *
from .forms import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def index(request):
    if request.user.is_authenticated:
        return redirect('cashier:menu')
    if request.method == 'POST':
        email = request.POST['email']
        try:
            user= User.objects.get(email = email)
        except:
            messages.error(request, "the account doesn't exist")
        else:
            password = request.POST['password']
            user = authenticate(request, email=email, password =password)
            if user is None:
                messages.error(request, "email or password incorrect")
            else:
                login(request, user)
                account = Account.objects.get(client=user)
                try:
                    credit_card = CreditCard.objects.get(account=account)
                except:
                    return redirect("cashier:card_activation")
                else:
                    return redirect('cashier:menu')       

    context = {

    }
    return render(request, "cashier/index.html", context )


def sign_up(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            account = Account.objects.create(client=user)
            try:
                credit_card = CreditCard.objects.get(account=account)
            except:
                return redirect("cashier:card_activation")
            else:
                return redirect('cashier:menu')       

        else:
            messages.error(request, "something went wrong during registration")
    form = UserRegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'cashier/sign_up.html', context)


@login_required(login_url='cashier:index')
def card_activation(request):
    if request.method == 'POST':
        form = CardActivation(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            account = Account.objects.get(client=request.user)
            card.account = account
            card.save()
            return redirect('cashier:menu') 
        else:
            messages.error(request, f'your credit card password is already been used by another account, please use another')      
    form = CardActivation()
    context = {
        'form': form
    }
    return render(request, 'cashier/card_activation.html', context)


@login_required(login_url='cashier:index')
def menu(request):
    user = request.user
    account = Account.objects.get(client=user)
    card = CreditCard.objects.get(account = account)
    context = {}
    if card.activation == False:
        messages = [f'your credit card is blocked']
        context.update({'messages': messages})
    return render(request, 'cashier/menu.html', context)


@login_required(login_url='cashier:index')
def logout_user(request):
    logout(request)
    return redirect('cashier:index')


@login_required(login_url='cashier:index')
def check_balance(request):
    user = request.user
    account = Account.objects.get(client=user)
    context = {
        'account': account
    }
    return render(request, 'cashier/check_balance.html', context)


@login_required(login_url='cashier:index')
def card_validation(request, trans, tries):
    user = request.user
    account = Account.objects.get(client=user)
    card = CreditCard.objects.get(account = account)
    context = {}
    # task for new session: fix the try loop problem
    if card.activation == False:
        e_messages = [f'sorry, your credit card is blocked']
        context = {
            'messages': e_messages
        }
        return render(request, 'cashier/menu.html', context)

    if request.method == 'POST':
        if request.GET.get('q') == 'deposit_money':
            money = request.POST['money']
            if (float(money) > account.balance) and request.user.email != request.POST['user']:
                messages = [f'insufficient balance to complete the transaction']
                context = {
                    'messages': messages
                }
                return render(request, 'cashier/deposit.html', context)
            else:
                username = request.POST['user']
                user = User.objects.get(email=username)
                account = Account.objects.get(client=user)
                context.update({'account': account.pk, 'money': money})

        elif request.GET.get('q') == 'purchase_tickets':
            tickets = request.POST['tickets']
            money = float(tickets)*10000
            if float(money) > account.balance:
                messages = [f'insufficient balance to complete the transaction']
                context = {
                    'messages': messages
                }
                return render(request, 'cashier/purchase_tickets.html', context)
            else:
                context.update({'tickets': tickets})
        elif request.GET.get('q') == 'withdraw_money':
            money = request.POST['money']
            if float(money) > account.balance:
                messages = [f'insufficient balance to complete the transaction']
                context = {
                    'messages': messages
                }
                return render(request, 'cashier/withdraw_money.html', context)
            else:
                context.update({'money_withdraw': money})

        else:
            if card.password == request.POST['card-password']:
                if trans == 1:
                    return redirect('cashier:check_balance')
                elif trans == 2:
                    tickets = int(request.POST.get('tickets'))
                    money = tickets*10000
                    request_account= Account.objects.get(client=request.user)
                    request_account.balance -= money
                    request_account.save()
                    s_messages = [f'your transaction has been successful']
                    context = {
                    's_messages': s_messages
                    }
                    return render(request, 'cashier/menu.html', context)

                elif trans == 3:
                    money = float(request.POST.get('money'))
                    request_account= Account.objects.get(client=request.user)
                    account = request.POST.get('account')
                    account = Account.objects.get(pk=int(account))
                    if request_account != account:
                        request_account.balance -= money
                        request_account.save()
                    account.balance += money
                    account.save()                
                    s_messages = [f'your transaction has been successful']
                    context = {
                    's_messages': s_messages
                    }
                    return render(request, 'cashier/menu.html', context)

                elif trans == 4:
                    money = float(request.POST.get('money'))
                    request_account= Account.objects.get(client=request.user)
                    request_account.balance -= money
                    request_account.save()
                    s_messages = [f'your transaction has been successful']
                    context = {
                    's_messages': s_messages
                    }
                    return render(request, 'cashier/menu.html', context)
    
            else:
                tries += 1
                if tries == card.id_limit:
                    card.activation=False
                    card.save()
                    messages = [f'wrong password, your credit card has been blocked']
                    context = {
                        'messages': messages
                    }
                    return render(request, 'cashier/menu.html', context)
                messages = [f'wrong password, you have {3-tries} tries left']
                context = {
                'trans': trans, 
                'tries': tries,
                'messages': messages
                    }
                return render(request, 'cashier/card_validation.html', context)
    context.update({
        'trans': trans, 
        'tries': tries,
        })
    return render(request, 'cashier/card_validation.html', context)


@login_required(login_url='cashier:index')
def deposit(request):
    context = {}
    return render(request, 'cashier/deposit.html', context)


@login_required(login_url='cashier:index')
def deposit_money(request):    
    context = {}
    if request.GET.get('q') == 'another_account':
        context.update({'another': 'another'})
    else:
        context.update({'self': 'self'})
    return render(request, 'cashier/deposit_money.html', context)


@login_required(login_url='cashier:index')
def purchase_tickets(request):
    context = {}
    return render(request, 'cashier/purchase_tickets.html', context)


@login_required(login_url='cashier:index')
def withdraw_money(request):
    context = {}
    return render(request, 'cashier/withdraw_money.html', context)

automatic_cashier/cashier/templates/cashier/card_activation.html
{% extends "main.html" %}

{% block content %}
    <section class='log-in d-flex flex-column justify-content-center align-items-center container-fluid'>
        <h3>just one more step to start!</h3>
        <form class='identification d-flex flex-column justify-content-center align-items-center' method='POST' action=''>
            {% csrf_token %}
            {% if messages %}
            {% for m in messages %}
            <div class="alert alert-danger" role="alert">
                {{m}}
                </div>
                {% endfor %}
            {% endif %}
            {{form}}
            <button class="btn btn-primary" type="submit">submit</button>
        </form>

    </section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/card_validation.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>

    <section class='log-in d-flex flex-column justify-content-center align-items-center container-fluid'>
        <h3>digit your credit card password</h3>
        <form class='identification d-flex flex-column justify-content-center align-items-center' method='POST' action=' {% url 'cashier:card_validation'  trans tries %} '>
            {% csrf_token %}
            {% if messages %}
            {% for m in messages %}
            <div class="alert alert-danger" role="alert">
                {{m}}
                </div>
                {% endfor %}
            {% endif %}
            <input class='form-control password' name='card-password' type="password" maxlength='4' placeholder='####'>
            {% if account and money %}
                <input name='account' class='d-none' type="text" value={{account}}>
                <input name='money' class='d-none' type="text" value={{money}}>
            {% endif %}
            {% if tickets %}
            <input name='tickets' class='d-none' type="text" value={{tickets}}>

            {% endif %}
            {% if money_withdraw %}
            <input name='money' class='d-none' type="text" value={{money_withdraw}}>
            {% endif %}
            <button class="btn btn-primary" type="submit">submit</button>
        </form>

    </section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/check_balance.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>

<section class='balance-container d-flex flex-column justify-content-center text-center align-items-center container'>
    <h4><span class='title'>Welcome:</span><br> <span class='text'>{{request.user}}</span>  </h4>
    <p><span class='title'>Email:</span> <br> <span class='text'>{{request.user.email}}</span></p>
    <p><span class='title'>Balance:</span> <br> <span class='text'>{{account.balance|floatformat:2}}$</span></p>
    <p><span class='title'>Opening date:</span> <br> <span class='text'>{{account.opening_date}}</span></p>

</section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/deposit.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>
    <section class='menu-container d-flex flex-column justify-content-center align-items-center container'>
        <h4>Where do yo want to deposit money?</h4>    
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% endif %}
        <div class='menu row d-flex justify-content-between container'>
            <a  href='{% url 'cashier:deposit_money' %}?q=another_account  ' class='col-12 col-md-6 '><i class="bi bi-people"></i>Another account </a>
            <a  href=' {% url 'cashier:deposit_money' %}?q=self_account ' class='col-12 col-md-6 even'>Self account<i class="bi bi-person"></i></a>

        </div>

    </section>

{% endblock content %}      

automatic_cashier/cashier/templates/cashier/deposit_money.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>

<section class='deposit-container d-flex flex-column justify-content-center text-center align-items-center container'>
    <form class='d-flex flex-column justify-content-center align-items-center'  action=" {% url 'cashier:card_validation' 3 0 %}?q=deposit_money" method='POST'>
        {% csrf_token %}
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% endif %}

        <h4><span class='title'>Deposit money:</span><br> </h4>
        <input name='money' step="0.01" class='form-control' type="number" min="100" max="999999" maxlength='6' placeholder='$$$$$$' required>
        {% if another %}
            <h4><span class='title'>Account:</span><br> </h4>
            <input  name='user' class='form-control' type="email" placeholder='account email-user' required>
        {% else %}
            <input  name='user' class='d-none' value={{request.user.email}}  type="email" required>

        {% endif %}
    
    
        <button class="btn btn-primary" type="submit">Deposit</button>
    
    </form>


</section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/index.html
{% extends "main.html" %}

{% block content %}
    <section class='log-in d-flex flex-column justify-content-center align-items-center container-fluid'>
        <h1>Welcome to the banky digital ATM</h1>
        <form class='identification d-flex flex-column justify-content-center align-items-center' method='POST' action=''>
            <h4 class='log_title'>access the cashier</h4>
            {% csrf_token %}
            {% if messages %}
            {% for m in messages %}
            <div class="alert alert-danger" role="alert">
                {{m}}
                </div>
                {% endfor %}
            {% endif %}
            <input placeholder="indicate your email address" class='form-control' name="email" type="email">
            <input placeholder="indicate your account password" class='form-control' name="password" type="password">
            <button class="btn btn-primary" type="submit">access</button>
            <a href=" {% url 'cashier:sign_up'  %} ">haven't created an account yet?</a>
        </form>

    </section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/menu.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:logout'  %} "><i class="bi bi-arrow-left-circle-fill"></i> Exit</a>
        {% endif %}
    </section>
</nav>
    <section class='menu-container d-flex flex-column justify-content-center align-items-center container'>
        <h4>welcome back {{request.user}} </h4>
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% elif s_messages %}
        {% for m in s_messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{m}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
            {% endfor %}
            
        {% endif %}

        <div class='menu row d-flex justify-content-between container'>
            <a  href='{% url 'cashier:card_validation' 1 0 %} ' class='col-md-6 '><i class="bi bi-piggy-bank"></i>   Check Balance </a>
            <a  href=' {% url 'cashier:purchase_tickets' %} ' class='col-md-6 even'>Purchase Tickets <i class="bi bi-ticket-perforated"></i></a>
            <a  href='{% url 'cashier:deposit' %}' class='col-md-6'><i class="bi bi-wallet"></i>   Deposit Money </a>
            <a  href='{% url 'cashier:withdraw_money' %}' class='col-md-6 even'>Withdraw Money <i class="bi bi-wallet2"></i></a>

        </div>

    </section>

{% endblock content %}      

automatic_cashier/cashier/templates/cashier/purchase_tickets.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>

<section class='deposit-container d-flex flex-column justify-content-center text-center align-items-center container'>
    <form class='d-flex flex-column justify-content-center align-items-center'  action=" {% url 'cashier:card_validation' 2 0 %}?q=purchase_tickets" method='POST'>
        {% csrf_token %}
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% endif %}
        <h4><span class='title'>Purchase theater tickets:</span><br> </h4>
        <input name='tickets' class='form-control' type="number" min="1" max="4" placeholder='tickets' required>
        <p>ticket price: 10000$</p>    
    
        <button class="btn btn-primary" type="submit">Purchase</button>
    
    </form>


</section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/sign_up.html
{% extends "main.html" %}

{% block content %}
<section class='log-in d-flex flex-column justify-content-center align-items-center container-fluid'>
    <form class='identification d-flex flex-column justify-content-center align-items-center' method='POST' action=''>
        <h4 class='log_title'>sign up</h4>
        <br>
        {% csrf_token %}
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% endif %}
        {{form}}
        <p>Your password can’t be too similar to your other personal information. <br>
            Your password must contain at least 8 characters. <br>
            Your password can’t be a commonly used password. <br>
            Your password can’t be entirely numeric. <br>
            
            </p>
        <button class="btn btn-primary" type="submit">start account</button>
    </form>

</section>


{% endblock content %}

automatic_cashier/cashier/templates/cashier/withdraw_money.html
{% extends "main.html" %}

{% block content %}
<nav>
    <section>
        {% if request.user.is_authenticated %}
            <a class='exit' href=" {% url 'cashier:menu'  %} "><i class="bi bi-arrow-left-circle-fill"></i>Cancel transaction</a>
        {% endif %}
    </section>
</nav>

<section class='deposit-container d-flex flex-column justify-content-center text-center align-items-center container'>
    <form class='d-flex flex-column justify-content-center align-items-center'  action=" {% url 'cashier:card_validation' 4 0 %}?q=withdraw_money" method='POST'>
        {% csrf_token %}
        {% if messages %}
        {% for m in messages %}
        <div class="alert alert-danger" role="alert">
            {{m}}
            </div>
            {% endfor %}
        {% endif %}

        <h4><span class='title'>Withdraw money:</span><br> </h4>
        <input name='money' step="0.01" class='form-control' type="number" min="100" max="999999" maxlength='6' placeholder='$$$$$$' required>
    
    
        <button class="btn btn-primary" type="submit">Withdraw</button>
    
    </form>


</section>


{% endblock content %}